### PR TITLE
ANVGL-82 and ANVGL-85

### PR DESCRIPTION
**Pull request by joshvote**
Don't pull until https://github.com/AuScope/portal-core/pull/141 is pulled into portal-core.

Tidied up all sorts of JobBuilder GUI issues with the ANVGL-85 commit. 

ANVGL-82 fixes up the currently erroneous S3 bucket creation (which currently depends on the STS role which it can't actually know until the cloud formation script runs and generates the STS role...)

### CODE REVIEW

**Comment by squireg** [comment]
This removes the code in JobUploadForm.js that associates the job with the default series (createSeries function and call to it), with the result that the job no longer shows up in the job monitor after submission. The jobs are supposed to belong to the default series, even if the concept is no longer user visible. I added the createSeries stuff when I made the no-series changes recently.

Perhaps JUF.js is not the best place to make the association, but that's how it was done in the vgl code I appropriated. A better solution might be to make the association on job creation in JobBuilderController or similar? In any case, this pull request does not work as intended currently - the job starts, but can't be monitored.

**Comment by squireg** [comment]
screenshot - 290316 - 15 21 52

**Comment by joshvote** [comment]
@squireg is right, I misinterpreted the new way of managing series. I'll revert and retest before appending more commits. iirc I removed it initially due to some internal NPE's, need to retest to veritfy.

**Comment by joshvote** [comment]
This has been rolled into #25 , Disregard this PR

**Pull request closed without merging**
