### PR TITLE
Alphanumerical layer ordering

### PR DESCRIPTION
**Pull request by manusiddhartha**
ANVGL17: Change the order of knownLayers to be alphanumeric

### CODE REVIEW

**Comment by oehm-smith** [comment]
It looks like you are doing too much in this commit and more than "Alphanumerical layer ordering".  Are there separate issues for all the work or should you be combining it all into one?  It is good to have atomic commits.

**Comment by squireg** [comment]
What version of portal-core are you using? With the current snapshot of portal-core the order property of the KnownLayer class has int type. This causes an error on startup when it tries to parse the order properties of your known layer beans (strings like "1_Geoscience..._2"). The GA portal-core fork appears to have the same issue.

**Comment by manusiddhartha** [comment]
Of the two commits, the first commit is the resolution to the issue and the second commit re-orders the beans in the sequence they render to the user for better readability (but gives the impression all of the file has been modified). On the properties itself however, there was no change on the second commit.

**Comment by manusiddhartha** [comment]
I've already sent a pull request to portal-core that has the change for it go from 'int' to 'string', which will be reviewed tomorrow. It shouldn't be merged until that one is in play, sorry about the issue it caused.

**Comment by squireg** [comment]
No worries, I missed the portal-core pull request. To make a reviewer's life easier, please include a note with the pull request about dependencies on other pull requests, or any other external dependencies or required changes to configs etc.

**Comment by manusiddhartha** [comment]
The external dependency is now resolved as the branch has been merged to portal-core, cheers.  https://github.com/AuScope/portal-core/pull/72

**Pull request merged**
